# Generated by Django 2.2 on 2021-04-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoed_app', '0002_auto_20210403_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='purchase_link',
            field=models.CharField(default='ecoed', max_length=255),
            preserve_default=False,
        ),
    ]
