# Generated by Django 2.2 on 2021-04-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoed_app', '0003_book_purchase_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.CharField(default='img/mhyman.png', max_length=150),
            preserve_default=False,
        ),
    ]
