# Generated by Django 2.2 on 2021-04-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoed_app', '0004_book_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carbon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flights', models.PositiveIntegerField()),
                ('drives', models.PositiveIntegerField()),
                ('trains', models.PositiveIntegerField()),
                ('fp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_footprint', to='ecoed_app.User')),
            ],
        ),
    ]
